# version: "3.8" 

# all services to run when run docker compose command
# db
# app
services:
  db:
    image: postgres
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data       

  api:
    build: .
    container_name: "go-api-pg-comments"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      # has to match image name
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports: 
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack    

# mapping to local machine volumes
volumes:
  database_postgres:

# network to services communicate
networks:
  fullstack:
    driver: bridge